/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as IndexRouteImport } from './routes/index'

const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/insights': typeof InsightsRoute
  '/quests': typeof QuestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/insights': typeof InsightsRoute
  '/quests': typeof QuestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/insights': typeof InsightsRoute
  '/quests': typeof QuestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/badges' | '/insights' | '/quests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/badges' | '/insights' | '/quests'
  id: '__root__' | '/' | '/badges' | '/insights' | '/quests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  InsightsRoute: typeof InsightsRoute
  QuestsRoute: typeof QuestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  InsightsRoute: InsightsRoute,
  QuestsRoute: QuestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
